#=================================================
# https://github.com/danxiaonuo/blog
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

# 编译的名称
name: 自动部署okteto

on:  
  # 仓库触发工作流
  # repository_dispatch:
  # 编辑文件触发开始编译
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build-blog-okteto'
        required: true
        default: '自动编译博客'
  # 每天的5点钟自动更新
  #schedule:
  #   - cron: '0 21 * * *'
  # 点☆Star触发开始编译
  watch:  
     types: [started]


# 环境变量
env:
   # 源码仓库地址
   GITHUB_RROJECT: github.com/danxiaonuo/blog.git
   # 源码分支
   REPO_BRANCH: main
     

# 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    # 运行步骤
    steps:
    
    # 准备完毕
    - name: "准备完毕"
      uses: actions/checkout@v2
    
    # 克隆源码
    - name: "克隆源码"
      env:
          GITHUB_TOKEN: ${{ secrets.BLOG_TOKEN }}
      run: |
        git clone --depth 1 https://${{ env.GITHUB_TOKEN }}@$GITHUB_RROJECT -b $REPO_BRANCH blog
        cd blog && git submodule update --init --recursive
       
    - name: "登录okteto"
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "激活命名空间"
      uses: okteto/namespace@master
      with:
        name: danxiaonuo

    - name: "创建 stack"
      uses: okteto/deploy-stack@master
      with:
        build: "true"
    
    - name: 删除旧的GitHub-workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1    #保留多少个workflow不删除
